apiVersion: skaffold/v4beta3
kind: Config
manifests:
  rawYaml:
    - ./infra/k8s/*.yaml
build:
  artifacts:
    - image: oliverc96/auth
      platforms: ["linux/arm64"]
      context: auth
      sync:
        manual:
          - src: 'src/**/*.ts'
            dest: .
      docker:
        dockerfile: Dockerfile
    - image: oliverc96/client
      platforms: ["linux/arm64"]
      context: client
      sync:
        manual:
          - src: '**/*.{js,jsx,css}'
            dest: .
      docker:
        dockerfile: Dockerfile
    - image: oliverc96/tickets
      platforms: ["linux/arm64"]
      context: tickets
      sync:
        manual:
          - src: 'src/**/*.ts'
            dest: .
      docker:
        dockerfile: Dockerfile
    - image: oliverc96/orders
      platforms: ["linux/arm64"]
      context: orders
      sync:
        manual:
          - src: 'src/**/*.ts'
            dest: .
      docker:
        dockerfile: Dockerfile
    - image: oliverc96/expiration
      platforms: ["linux/arm64"]
      context: expiration
      sync:
        manual:
          - src: 'src/**/*.ts'
            dest: .
      docker:
        dockerfile: Dockerfile
    - image: oliverc96/payments
      platforms: ["linux/arm64"]
      context: payments
      sync:
        manual:
          - src: 'src/**/*.ts'
            dest: .
      docker:
        dockerfile: Dockerfile